#!/bin/bash
EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
    then
      echo "Usage: `basename $0` {project_name}"
      exit $E_BADARGS
fi
git clone ssh://$USER@review.pozytywnie.pl:29418/$1 $1 &&\
cd $1 &&\
gerrit-hook
