#!/bin/bash
EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
    then
      echo "Usage: `basename $0` {project_name} {branch_name}"
      exit $E_BADARGS
fi

pushd /tmp
git init $1
pushd $1
gerrit-add-remote $1
popd
popd
if [ -a ".git" ]; then
    DIR=`pwd`
    pushd /tmp/$1
    git remote add cache $DIR
    git fetch cache
    popd
fi;
pushd /tmp/$1
git fetch origin
git push origin origin/develop:refs/heads/$2
popd
rm /tmp/$1 -rf
